spring:
  application:
    name: StoneHard

  security:
    user:
      name: bok
      password: 123123
      roles: USER

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stone_hard?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 456123

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql: TRACE
      springframework:
        security: DEBUG

server:
  port: 8080
